std_msgs/Header header
geometry_msgs/Pose particles_mean_pose_ego
geometry_msgs/Pose particles_mean_pose_left
geometry_msgs/Pose particles_mean_pose_right
int32 auv_id_ego
int32 auv_id_left
int32 auv_id_right
---
std_msgs/Empty resp


